KE32:	keyExchange3-2.cpp 
	g++ keyExchange3-2.cpp -o KE32 -std=c++11
ExKE32: KE32
	./KE32	


KE42:	keyExchange4-2.cpp 
	g++ keyExchange4-2.cpp -o KE42 -std=c++11
ExKE42: KE42
	./KE42


KE43:	keyExchange4-3.cpp 
	g++ keyExchange4-3.cpp -o KE43 -std=c++11
ExKE43: KE43
	./KE43


KE84:	keyExchange8-4.cpp 
	g++ keyExchange8-4.cpp -o KE84 -std=c++11
ExKE84: KE84
	./KE84


KE122:	keyExchange12-2.cpp 
	g++ keyExchange12-2.cpp -o KE122 -std=c++11
ExKE122: KE122
	./KE122


